version: "3.8"
services:
  app:
    container_name: rcm_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    environment:
      - DB_PASSWORD="arangodb@rcm"
