version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rcm_app_dev
    depends_on:
      - db
    restart: always
    env_file: .env
    ports:
      - $NODE_HOST_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./src:/app/src
      - /app/node_modules

  db:
    image: arangodb:3.9
    container_name: rcm_db_dev
    restart: always
    environment:
      - ARANGO_ROOT_PASSWORD=$ARANGO_ROOT_PASSWORD
    ports:
      - $ARANGO_HOST_PORT:$ARANGO_DOCKER_PORT
    volumes:
      - arangodb_data_container:/var/lib/arangodb3

volumes:
  arangodb_data_container:
